# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(360, 565)
        MainWindow.setStyleSheet("background-color: black")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")


        self.pct_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("%"))
        self.pct_Button.setGeometry(10, 110, 75, 75)
        self.pct_Button.setStyleSheet("border: 2px solid black;"
                                      "border-radius: 37;"
                                      "background-color: #a0a0a0")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.pct_Button.setFont(font)
        self.pct_Button.setObjectName("pct_Button")

        self.Button7 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("7"))
        self.Button7.setGeometry(QtCore.QRect(10, 195, 75, 75))
        self.Button7.setStyleSheet("border: 2px solid black;"
                                      "border-radius: 37;"
                                      "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button7.setFont(font)
        self.Button7.setObjectName("Button7")

        self.delete_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.backspace())
        self.delete_Button.setGeometry(QtCore.QRect(187, 110, 75, 75))
        self.delete_Button.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #a0a0a0;"
                                   "color: solid black")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.delete_Button.setFont(font)
        self.delete_Button.setObjectName("delete_Button")

        self.clear_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("C"))
        self.clear_Button.setGeometry(QtCore.QRect(98, 110, 75, 75))
        self.clear_Button.setStyleSheet("border: 2px solid black;"
                                         "border-radius: 37;"
                                         "background-color: #a0a0a0;"
                                         "color: solid black")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.clear_Button.setFont(font)
        self.clear_Button.setObjectName("clear_Button")

        self.divide_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("/"))
        self.divide_Button.setGeometry(QtCore.QRect(275, 110, 75, 75))
        self.divide_Button.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #f69906;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.divide_Button.setFont(font)
        self.divide_Button.setObjectName("divide_Button")

        self.Button5 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("5"))
        self.Button5.setGeometry(QtCore.QRect(98, 280, 75, 75))
        self.Button5.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button5.setFont(font)
        self.Button5.setObjectName("Button5")

        self.decimal_Button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.decimal_press())
        self.decimal_Button.setGeometry(QtCore.QRect(187, 450, 75, 75))
        self.decimal_Button.setStyleSheet("border: 2px solid black;"
                                          "border-radius: 37;"
                                          "background-color: #313131;"
                                          "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.decimal_Button.setFont(font)
        self.decimal_Button.setObjectName("decimal_Button")

        self.Button1 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("1"))
        self.Button1.setGeometry(QtCore.QRect(10, 365, 75, 75))
        self.Button1.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button1.setFont(font)
        self.Button1.setObjectName("Button1")

        self.Button4 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("4"))
        self.Button4.setGeometry(QtCore.QRect(10, 280, 75, 75))
        self.Button4.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button4.setFont(font)
        self.Button4.setObjectName("Button4")

        self.mult_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("*"))
        self.mult_Button.setGeometry(QtCore.QRect(275, 195, 75, 75))
        self.mult_Button.setStyleSheet("border: 2px solid black;"
                                         "border-radius: 37;"
                                         "background-color: #f69906;"
                                         "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.mult_Button.setFont(font)
        self.mult_Button.setObjectName("mult_Button")

        self.Button9 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("9"))
        self.Button9.setGeometry(QtCore.QRect(187, 195, 75, 75))
        self.Button9.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button9.setFont(font)
        self.Button9.setObjectName("Button9")

        self.Button8 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("8"))
        self.Button8.setGeometry(QtCore.QRect(98, 195, 75, 75))
        self.Button8.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button8.setFont(font)
        self.Button8.setObjectName("Button8")

        self.min_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("-"))
        self.min_Button.setGeometry(QtCore.QRect(275, 280, 75, 75))
        self.min_Button.setStyleSheet("border: 2px solid black;"
                                         "border-radius: 37;"
                                         "background-color: #f69906;"
                                         "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.min_Button.setFont(font)
        self.min_Button.setObjectName("min_Button")

        self.Button6 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("6"))
        self.Button6.setGeometry(QtCore.QRect(187, 280, 75, 75))
        self.Button6.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button6.setFont(font)
        self.Button6.setObjectName("Button6")

        self.Button3 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("3"))
        self.Button3.setGeometry(QtCore.QRect(187, 365, 75, 75))
        self.Button3.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button3.setFont(font)
        self.Button3.setObjectName("Button3")

        self.Button0 = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.button_press("0"))
        self.Button0.setGeometry(QtCore.QRect(10, 450, 160, 75))
        self.Button0.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "text-align: left;"
                                   "padding: 21px;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button0.setFont(font)
        self.Button0.setObjectName("Button0")

        self.equal_Button = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.solve())
        self.equal_Button.setGeometry(QtCore.QRect(275, 450, 75, 75))
        self.equal_Button.setStyleSheet("border: 2px solid black;"
                                        "border-radius: 37;"
                                        "background-color: #f69906;"
                                        "color: white")

        font = QtGui.QFont()
        font.setPointSize(26)
        self.equal_Button.setFont(font)
        self.equal_Button.setObjectName("equal_Button")

        self.Button2 = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("2"))
        self.Button2.setGeometry(QtCore.QRect(98, 365, 75, 75))
        self.Button2.setStyleSheet("border: 2px solid black;"
                                   "border-radius: 37;"
                                   "background-color: #313131;"
                                   "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Button2.setFont(font)
        self.Button2.setObjectName("Button2")

        self.plus_Button = QtWidgets.QPushButton(self.centralwidget, clicked= lambda: self.button_press("+"))
        self.plus_Button.setGeometry(QtCore.QRect(275, 365, 75, 75))
        self.plus_Button.setStyleSheet("border: 2px solid black;"
                                         "border-radius: 37;"
                                         "background-color: #f69906;"
                                         "color: white")
        font = QtGui.QFont()
        font.setPointSize(26)
        self.plus_Button.setFont(font)
        self.plus_Button.setObjectName("plus_Button")


        self.display_label = QtWidgets.QLabel(self.centralwidget)
        self.display_label.setGeometry(QtCore.QRect(10, 10, 340, 90))
        self.display_label.setStyleSheet("background-color: black;"
                                         "color: white;"
                                         "border: 0px")
        font = QtGui.QFont()
        font.setPointSize(36)

        self.display_label.setFont(font)
        self.display_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.display_label.setFrameShape(QtWidgets.QFrame.Box)
        self.display_label.setFrameShadow(QtWidgets.QFrame.Plain)
        self.display_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.display_label.setObjectName("display_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 360, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    # Solve
    def solve(self):
        screen = self.display_label.text()
        try:
            solution = eval(screen)
            self.display_label.setText(str(solution))
        except:
            self.display_label.setText("ERROR")
    # Backspace
    def backspace(self):
        screen = self.display_label.text()
        screen = screen[:-1]
        self.display_label.setText(screen)


    # Decimal
    def decimal_press (self):
        operations = ["+", "-", "×", "÷", "%"]
        screen = self.display_label.text()
        if "." not in screen:
            self.display_label.setText(f'{screen}.')      
        else:
            for i in operations:
                if i in screen and screen[-1]!=".":
                    self.display_label.setText(f'{screen}.')


    def button_press(self, pressed):
        if pressed == "C":
            self.display_label.setText("0")
        else:
        # If entry box contains just a 0, it is deleted before next input
            if self.display_label.text() == "0":
                self.display_label.setText("")
            #  f string joins all inputs
            self.display_label.setText(f'{self.display_label.text()}{pressed}')

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pct_Button.setText(_translate("MainWindow", "%"))
        self.Button7.setText(_translate("MainWindow", "7"))
        self.delete_Button.setText(_translate("MainWindow", "⌫"))
        self.clear_Button.setText(_translate("MainWindow", "C"))
        self.divide_Button.setText(_translate("MainWindow", "÷"))
        self.Button5.setText(_translate("MainWindow", "5"))
        self.decimal_Button.setText(_translate("MainWindow", "."))
        self.Button1.setText(_translate("MainWindow", "1"))
        self.Button4.setText(_translate("MainWindow", "4"))
        self.mult_Button.setText(_translate("MainWindow", "×"))
        self.Button9.setText(_translate("MainWindow", "9"))
        self.Button8.setText(_translate("MainWindow", "8"))
        self.min_Button.setText(_translate("MainWindow", "-"))
        self.Button6.setText(_translate("MainWindow", "6"))
        self.Button3.setText(_translate("MainWindow", "3"))
        self.Button0.setText(_translate("MainWindow", "0"))
        self.equal_Button.setText(_translate("MainWindow", "="))
        self.Button2.setText(_translate("MainWindow", "2"))
        self.plus_Button.setText(_translate("MainWindow", "+"))
        self.display_label.setText(_translate("MainWindow", "0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
